
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfP824FRZuFZV6i3aTqthY103bDTBpvc',
    appId: '1:1077340389690:web:61579132efabb1facb9003',
    messagingSenderId: '1077340389690',
    projectId: 'student-project-manager-d2bcc',
    authDomain: 'student-project-manager-d2bcc.firebaseapp.com',
    storageBucket: 'student-project-manager-d2bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIsvmMW-oNNAQzqwyX54BdWKRTcJ_AvcU',
    appId: '1:1077340389690:android:8b62a305e3a0bfc8cb9003',
    messagingSenderId: '1077340389690',
    projectId: 'student-project-manager-d2bcc',
    storageBucket: 'student-project-manager-d2bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjxsaP7mCUHav2nlWxKU8kXd8Ypu0qAQ',
    appId: '1:1077340389690:ios:6d4f5e13312a5393cb9003',
    messagingSenderId: '1077340389690',
    projectId: 'student-project-manager-d2bcc',
    storageBucket: 'student-project-manager-d2bcc.firebasestorage.app',
    iosBundleId: 'com.example.studentProjectManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjxsaP7mCUHav2nlWxKU8kXd8Ypu0qAQ',
    appId: '1:1077340389690:ios:6d4f5e13312a5393cb9003',
    messagingSenderId: '1077340389690',
    projectId: 'student-project-manager-d2bcc',
    storageBucket: 'student-project-manager-d2bcc.firebasestorage.app',
    iosBundleId: 'com.example.studentProjectManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEfP824FRZuFZV6i3aTqthY103bDTBpvc',
    appId: '1:1077340389690:web:fb26de1bf3a58aeecb9003',
    messagingSenderId: '1077340389690',
    projectId: 'student-project-manager-d2bcc',
    authDomain: 'student-project-manager-d2bcc.firebaseapp.com',
    storageBucket: 'student-project-manager-d2bcc.firebasestorage.app',
  );

}